### ISSUE TITLE
Linebreaks disappear

### ISSUE THREAD

**Issue by flodmotorgrodan** [DFRobot/uPyCraft_src#1]
Using version "uPyCraft_V0.29.exe" on Windows7 when adding code to an existing *.py file and saving - the saved file sometimes has multiple lines of code with no linebreaks.

If IDE is still open and problematic code section lines are copied and pasted to another linebreaks are copied ok.

Not sure what triggers the loss of linebreaks yet.

It is typically noticed after project is debugged and works fine. When source files are reopened you find them not properly saved. If you are lucky you may be able to restore healthy files from the device.

**Comment by ouki-wang** [comment]
@flodmotorgrodan sorry for the inconvenience, the further version will fix the linebreaks problem.
