### ISSUE TITLE
Can not build this source

### ISSUE THREAD

**Issue by nbxtruong** [DFRobot/uPyCraft_src#2]
When I run file uPyCraft.py on Geany IDE by using Python3. I have this errors:

/home/nbxtruong
/home/nbxtruong/AppData/Local/uPyCraft/temp/
/home/nbxtruong/AppData/Local/uPyCraft/examples
Traceback (most recent call last):
  File "uPyCraft.py", line 2574, in <module>
    main=MainWidget()
  File "uPyCraft.py", line 84, in __init__
    self.setFont()
  File "uPyCraft.py", line 184, in setFont
    for filename in fonts:
UnboundLocalError: local variable 'fonts' referenced before assignment

------------------
(program exited with code: 1)
Press return to continue

**Comment by nbxtruong** [comment]
I am using Ubuntu 16.04-64bit and I install all pyqt4, qsci, pyserial and pyflakes. My python version is 3.5.2

**Comment by ouki-wang** [comment]
@nbxtruong the current code only suport the windows system, the other versions will be updated in the future , contains the mac , linux.

**Comment by nbxtruong** [comment]
Thank you @ouki-wang
