### ISSUE TITLE
build uPyCraft with PyQt5 ?

### ISSUE THREAD

**Issue by jiapei100** [DFRobot/uPyCraft_src#9]
I changed all **PyQt4** to **PyQt5**, and have **uPyCraft** successfully built under folder **dist**.
However, I failed to run **uPyCraft** with the following **ERROR** messages:

```
$ ./uPyCraft 
Traceback (most recent call last):
  File "uPyCraft.py", line 4, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'
[4909] Failed to execute script uPyCraft
```

Any suggestions?
Pei

**Comment by jhlucky** [comment]
current version sup PyQt4.

**Comment by jhlucky** [comment]
No module named 'PyQt5.QtWidgets', Did not find the Widget module, maybe the pyqt installation error, you can try other versions. Execute the python terminal and execute it before running the program:
 from PyQt5.QtGui import *
from PyQt4.QtCore import *
from PyQt4        import Qsci

**Comment by jiapei100** [comment]
@jhlucky 
The solution is 

```
from PyQt5.QtWidgets import *
```


Cheers
Pei
